fix: må sjekke at filene og katalogene eksisterer

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -86,10 +86,21 @@ runs:
       shell: bash
       id: "setup"
       run: |
+        if [ ! -d "${{ inputs.docker_context }}" ]; then
+          echo "::error ::Docker context not found: ${{ inputs.docker_context }}."
+          exit 1
+        fi
+
         dockerfile="${{ inputs.docker_context }}/Dockerfile"
-        if [ ! -d "${{ inputs.dockerfile }}" ]; then
+        if [ -n "${{ inputs.dockerfile }}" ]; then
           dockerfile="${{ inputs.dockerfile }}"
         fi
+
+        if [ ! -f "$dockerfile" ]; then
+        echo "::error ::Dockerfile not found: $dockerfile. Do you need to prepend context or working directory?"
+          exit 1
+        fi
+
         echo "DOCKERFILE=$dockerfile" >> $GITHUB_OUTPUT
 
         suffix="${{ inputs.image_suffix }}"
